name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure environment
      run: sudo apt-get install -y meson flex bison
    - name: make
      run: make
    - name: clean
      run: make clean
